name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Enable required services (idempotent)
        run: |
          gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com

      - name: Build backend image (Cloud Build)
        working-directory: backend
        run: |
          gcloud builds submit --tag gcr.io/${GCP_PROJECT_ID}/pristilbud-backend

      - name: Create backend env file for Cloud Run
        working-directory: backend
        run: |
          echo "GOOGLE_CREDENTIALS_JSON: '${{ secrets.SHEETS_CREDENTIALS_JSON }}'" > .cloudrun.env.yaml

      - name: Deploy backend to Cloud Run
        working-directory: backend
        run: |
          gcloud run deploy pristilbud-backend \
            --image gcr.io/${GCP_PROJECT_ID}/pristilbud-backend \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated \
            --env-vars-file .cloudrun.env.yaml

      - name: Resolve backend URL
        id: backend
        run: |
          URL=$(gcloud run services describe pristilbud-backend --region ${GCP_REGION} --format='value(status.url)')
          echo "url=${URL}" >> $GITHUB_OUTPUT

      - name: Build frontend image (Cloud Build) with backend URL
        working-directory: frontend
        run: |
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions _VITE_BACKEND_URL=${{ steps.backend.outputs.url }}

      - name: Deploy frontend to Cloud Run
        working-directory: frontend
        run: |
          gcloud run deploy pristilbud-frontend \
            --image gcr.io/${GCP_PROJECT_ID}/pristilbud-frontend \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated


